name: Análisis Estático de Código

on:
  pull_request:
    branches:
      - main  # Puedes ajustar la rama según tus necesidades

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: SonarQube Scan
      run: |
        ./gradlew sonarqube \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.organization=my_organization_key \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN  # Asegúrate de definir esta variable en la configuración de tu repositorio
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
